# frozen_string_literal: true

require "rbconfig"

require "scarpe/components/file_helpers"
require_relative "../../lib/shoes-spec/test_list"
require_relative "../../lib/shoes-spec/shoes_config"

include ShoesSpec
include Scarpe::Components::FileHelpers

task "shoes-spec" do
  scarpe_exe = which("scarpe")

  with_each_loaded_test(display_service: "scarpe-webview") do |metadata, app_code, test_code|
    STDERR.puts "ARGS: #{[metadata, app_code, test_code].inspect}"

    with_tempfiles(
      [
        ["shoes-spec-scarpe-test-app", app_code],
        ["shoes-spec-scarpe-test-code", test_code],
      ]) do |app_file, test_code_file|
        # TODO: env vars SCARPE_LOG_CONFIG, SCARPE_TEST_RESULTS, LOCALAPPDATA=Dir.tmpdir
        ENV["SCARPE_SHOES_SPEC_TEST"] = test_code_file
        system(RbConfig.ruby, scarpe_exe, "--dev", app_file)
    end
  end
end

task default: "shoes-spec"
