# frozen_string_literal: true

require_relative "scarpe_webview_runner"

task "shoes-spec" do
  include Scarpe::Webview::Runner
  report_webview_specs(config: "local-calzini")
  report_webview_specs(config: "local-tiranti")
end

task "shoes-spec-calzini" do
  include Scarpe::Webview::Runner
  report_webview_specs(config: "local-calzini")
end

task "shoes-spec-tiranti" do
  include Scarpe::Webview::Runner
  report_webview_specs(config: "local-tiranti")
end

task default: "shoes-spec"
