source "https://rubygems.org"

# Why the complexity? This Gemfile needs to work from here and from inside the pkg_dir.
scan_for_root = "../.."
loop do
  if File.expand_path(scan_for_root) == "/"
    raise "Can't find cases dir to get shoes-spec local path!"
  end
  if File.exist? File.expand_path(scan_for_root + "/cases")
    break # Found it!
  end
  scan_for_root += "/.."
end

shoes_spec_path = scan_for_root
scarpe_local_path = File.expand_path "#{shoes_spec_path}/../scarpe"
scarpe_wasm_local_path = File.expand_path "#{shoes_spec_path}/../scarpe-wasm"

gem "shoes-spec", path: shoes_spec_path

#gem "scarpe-wasm", path: scarpe_wasm_local_path
#gem "scarpe-components", path: "#{scarpe_local_path}/scarpe-components"
#gem "lacci", path: "#{scarpe_local_path}/lacci"

gem "scarpe-wasm", github: "scarpe-team/scarpe-wasm"
gem "scarpe-components", github: "scarpe-team/scarpe", glob: "scarpe-components/*.gemspec"
gem "lacci", github: "scarpe-team/scarpe", glob: "lacci/*.gemspec"

gem "wasify", github: "alawysdelta/wasify", branch: "ruby_3_3_and_later_ruby_wasm"

group :test do
  gem "rake"
  gem "minitest", "~> 5.0"
  gem "minitest-reporters"
  gem "capybara"
  gem "selenium-webdriver"
  gem "webrick"
end
