# frozen_string_literal: true

task "shoes-spec" do
  require_relative "scarpe_wasm_runner"
  include Scarpe::Wasm::Runner

  File.unlink File.join(__dir__, "sspec.json") rescue nil
  File.unlink File.expand_path(File.join(__dir__, "../../results/scarpe-wasm/results-wasm.yaml")) rescue nil

  run_all_shoes_specs
end

task "manual-shoes-spec" do
  require_relative "scarpe_wasm_runner"
  include Scarpe::Wasm::Runner

  File.unlink File.join(__dir__, "sspec.json") rescue nil
  File.unlink File.expand_path(File.join(__dir__, "../../results/scarpe-wasm/results-wasm.yaml")) rescue nil

  manual_shoes_spec_run
end

task default: "shoes-spec"
