source "https://rubygems.org"

shoes_spec_path = "../.."
scarpe_local_path = "#{shoes_spec_path}/../scarpe"

gem "shoes-spec", path: "../.."

gem "scarpe", path: scarpe_local_path
gem "scarpe-components", path: "#{scarpe_local_path}/scarpe-components"
gem "lacci", path: "#{scarpe_local_path}/lacci"

group :test do
  gem "minitest"
  gem "minitest-reporters"
end
