# frozen_string_literal: true

require_relative "gtk_scarpe_runner"

desc "Run shoes-spec tests for gtk-scarpe"
task "shoes-spec" do
  include Scarpe::GTK::Runner
  report_gtk_specs(config: "local-gtk")
end

task default: "shoes-spec"
