---
name: Regular Shoes-Spec Run vs Known Implementations
on:
  schedule:
    - cron:  '30 17 * * *'
  workflow_dispatch:

jobs:
  tests:
    name: Shoes-Spec Tests
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Install dependencies
        run: brew cleanup && brew install pkg-config portaudio pango pcre2 gobject-introspection
      - name: Configure gem dirs from Homebrew
        run: bundle config build.bloops --with-portaudio-dir=`brew --prefix portaudio`
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install wasi-vfs for wasify
        run: curl -LO https://github.com/kateinoigakukun/wasi-vfs/releases/download/v0.5.0/wasi-vfs-cli-x86_64-apple-darwin.zip && unzip wasi-vfs-cli-x86_64-apple-darwin.zip && mkdir -p bin && mv wasi-vfs bin/
      - name: Install gems for implementations
        run: cd implementations/scarpe-wasm && bundle update && cd ../scarpe-webview && bundle update && cd ../niente && bundle update && cd ../gtk-scarpe && bundle update && cd ..
      - name: Run Shoes-Spec tests
        run: PATH=`pwd`/bin:$PATH bundle exec rake shoes-spec
